name: Continuous integration and deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
  cd:
    needs: ci
    if: ${{ github.event_name == 'release' }}
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
