name: Continuous integration and deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
